#cloud-config

package_update: true

packages:
  - gstreamer1-devel
  - gstreamer1-plugins-base-devel
  - gstreamer1-plugins-good
  - gstreamer1-plugins-bad-free-devel
  - gstreamer1-plugin-libav
  - libdav1d
  - glib2-devel
  - fontconfig-devel
