#cloud-config

package_update: true

packages:
  - git
  - clang-devel
  - rust
  - gstreamer1-devel
  - gstreamer1-plugins-base-devel
  - gstreamer1-plugins-good
  - gstreamer1-plugins-bad-free-devel
  - gstreamer1-libav
  - dav1d-devel
