[workspace]
members = [
    "xtask",
    "sdk/sender/fcast-sender-sdk",
    "sdk/sender/examples/terminal",
    "senders/terminal",
    "sdk/sender/examples/desktop",
    "sdk/common/fcast-protocol",
    "sdk/mirroring_core",
    "senders/desktop",
    "senders/android",
    "fast",
    "sdk/file-server",
    "senders/android",
    "receivers/experimental/rcore",
    "receivers/experimental/desktop",
    "receivers/experimental/android"
]
resolver = "2"

[workspace.package]
license = "MIT"

[workspace.dependencies]
tokio = { version = "1.46.1", features = [ "full" ] }
serde = { version = "1.0.219", features = [ "derive" ] }
gst = { package = "gstreamer", version = "0.24.2" }
gst-app = { package = "gstreamer-app", version = "0.24.2" }
gst-video = { package = "gstreamer-video", version = "0.24.2" }
serde_json = "1.0"
thiserror = "2.0"
log = "0.4"
env_logger = "0.11.8"
mdns-sd = "0.17.1"
anyhow = "1"
tracing = "0.1"
tracing-subscriber = "0.3.20"
tracing-gstreamer = "0.9.0"
tracing-panic = "0.1.2"
parking_lot = "0.12.5"
slint = "1.14.1"
slint-build = "1.14.1"
clap = { version = "4.5", features = ["derive"] }
uuid = { version = "1.18.1", features = [ "v4" ] }
bytes = "1"
smallvec = { version = "1.15.1", features = ["serde"] }
smol_str = { version = "0.3.4", features = ["serde"] }
toml_edit = { version = "0.24", features = ["serde"] }
futures = "0.3.31"
lazy_static = "1.5"

[profile.release]
lto = "thin"
codegen-units = 1
strip = true
