[package]
name = "xtask"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
clap = { version = "4.5.40", features = [ "derive" ] }
xshell = "0.2.7"
serde = { version = "1.0.219", features = [ "derive" ] }
serde_json = "1.0.140"
anyhow = "1.0.98"
camino = { version = "1.1.10", features = [ "serde1" ] }
uniffi_bindgen = "0.29.4"